name: Run android tests in github runner

on: push

permissions:
    contents: read
    pull-requests: write

concurrency: 
    group: screenshot-test-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
  
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [27]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        

          
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: |
            npm install -g appium@v2.1.3
            appium -v
            appium &>/dev/null &
      - name: Install scrcpy on macOS
        run: |
          brew install scrcpy

      - name: Install UIA2 driver
        run: appium driver install uiautomator2
       
      - name: AVD cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: avd-cache
        with:
          path: |
              ~/.android/avd/*
              ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b # v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          arch: x86
          sdcard-path-or-size: 100M
          target: google_apis
          script: echo "Generated AVD snapshot for caching."

      - name: run android tests
        uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b # v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          arch: x86
          target: google_apis
          emulator-options: -no-snapshot -delay-adb
          script: |
                scrcpy --record output.mp4 &
                RECORDING_PID=$!
                mvn clean test -Pandroid 
                kill $RECORDING_PID

          
      - name: Publish Video
        uses: actions/upload-artifact@v2
        with:
          name: output.mp4
          path: output.mp4
